spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console   
  cache:
    cache-names:
    - rate-limit-buckets
    caffeine:
      spec: maximumSize=500,expireAfterAccess=3600s         
bucket4j:
  enabled: true
  filters:
  - cache-name: rate-limit-buckets
    url: /weather/*
    strategy: first
    http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
    rate-limits:
    - expression: "getHeader('X-api-key')"
      bandwidths:
      - capacity: 5
        time: 1
        unit: hours
resource:
  api_key: 8040a0ca16e4713b7d62e967510f1d57
  weather_url: https://api.openweathermap.org/data/2.5
server:
  error:
    include-message: always
    include-stacktrace: always